baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-flexsearch'

[module]
  replacements = 'github.com/gethinode/mod-flexsearch -> ../..'
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch"
  # [[module.imports.mounts]]
  #   source = "assets/scss/modules/flexsearch/flexsearch.scss"
  #   target = "static/flexsearch.css"
  [[module.imports.mounts]]
    source = "assets"
    target = "assets"
  [[module.imports.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"